version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
- package-ecosystem: nuget
  directory: "/abstractions/dotnet"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/abstractions/java"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/abstractions/typescript"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/authentication/dotnet/azure"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/authentication/java/azure"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/authentication/typescript/azure"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/serialization/dotnet/json"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/serialization/java/json"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/serialization/typescript/json"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/http/dotnet/httpclient"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/http/java/okhttp"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/http/typescript/fetch"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
