version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - generator
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/abstractions/ruby/microsoft_kiota_abstractions"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - Ruby
- package-ecosystem: bundler
  directory: "/serialization/ruby/json/microsoft_kiota_serialization"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - Ruby
- package-ecosystem: bundler
  directory: "/http/ruby/nethttp/microsoft_kiota_nethttplibrary"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
    - Ruby
