blank_issues_enabled: true
contact_links:
  - name: Question on use of kiota
    url: https://github.com/microsoft/kiota/discussions
    about: Please add your question in the discussions section of the repo
  - name: Question or Feature Request for the MS Graph API?
    url: https://aka.ms/msgraphsupport
    about: Report an issue or limitation with the MS Graph service APIs
