name: kiota_dart_generate
description: api generation
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  kiota_abstractions:
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: json
      path: packages/kiota_abstractions
  kiota_http:
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: json
      path: packages/kiota_http
  kiota_serialization_form:
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: json
      path: packages/kiota_serialization_form
  kiota_serialization_text:
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: json
      path: packages/kiota_serialization_text
  kiota_serialization_json:
    git:
      url: https://github.com/kiota-community/dart_kiota.git
      ref: json
      path: packages/kiota_serialization_json
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  lints: ^3.0.0
