name: Dotnet Core

on:
  push:
    branches: [ main ]
    paths: ['core/dotnet/**', '.github/workflows/**', 'scripts']
  pull_request:
    paths: ['core/dotnet/**', '.github/workflows/**', 'scripts']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./core/dotnet
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: ./scripts/updateNugetCredentials.ps1 -username "baywet" -apiToken "${{ secrets.PUBLISH_GH_TOKEN }}" -nugetFileAbsolutePath "./core/dotnet/nuget.config"
        shell: pwsh
      - name: Restore dependencies
        run: dotnet restore KiotaCore.sln
        working-directory: ${{ env.relativePath }}
      - name: Build
        run: dotnet build KiotaCore.sln --no-restore -c Release
        working-directory: ${{ env.relativePath }}
      - name: Test
        run: dotnet test KiotaCore.sln --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Publish
        run: dotnet publish KiotaCore.sln --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - name: Pack
        run: dotnet pack KiotaCore.sln --no-restore --no-build --verbosity normal -c Release
        working-directory: ${{ env.relativePath }}
      - uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/src/bin/Release/*.nupkg
      - run: git checkout ./core/dotnet/nuget.config
        if: always()
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/download-artifact@v2
        with:
          name: drop
      - run: dotnet nuget push "*.nupkg" --skip-duplicate -s https://nuget.pkg.github.com/microsoft/index.json -k ${{ secrets.PUBLISH_GH_TOKEN }}
