name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']
    paths: ['src/**', '.github/workflows/**']
env:
  REGISTRY: msgraphprod.azurecr.io
  IMAGE_NAME: public/openapi/kiota
jobs:
  push_to_registry:
    environment:
      name: acr
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to GitHub package feed
        uses: docker/login-action@v2.1.0 
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ env.REGISTRY }}
      - run: |
          $version = $Env:BRANCH_NAME -replace "refs/tags/v",""
          echo "::set-output name=version::${version}"
        shell: pwsh
        id: getversion
        if: contains(github.ref, 'refs/tags/v')
        env:
          BRANCH_NAME: ${{ github.ref }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Push to GitHub Packages - Nightly
        if: contains(github.ref, 'refs/head/main')
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,windows/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nightly
      - name: Push to GitHub Packages - Release
        if: contains(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,windows/amd64
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.getversion.outputs.version }}
