name: Java Serialization Json

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: ['serialization/java/json/**', '.github/workflows/**']
  pull_request:
    paths: ['serialization/java/json/**', '.github/workflows/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      relativePath: ./serialization/java/json
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Add execution right to the script
        run: chmod +x gradlew
        working-directory: ${{ env.relativePath }}
      - name: Build SDK project
        run: ./gradlew --no-daemon build
        working-directory: ${{ env.relativePath }}
        env:
          USERNAME: ${{ secrets.PUBLISH_GH_USERNAME }}
          TOKEN: ${{ secrets.PUBLISH_GH_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: drop
          path: |
            ${{ env.relativePath }}/lib/build/libs/*.jar
  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    environment:
      name: staging_feeds
    runs-on: ubuntu-latest
    env:
      relativePath: ./serialization/java/json
    needs: [build]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Add execution right to the script
        run: chmod +x gradlew
        working-directory: ${{ env.relativePath }}
      - name: Publish SDK project
        run: ./gradlew --no-daemon publish
        working-directory: ${{ env.relativePath }}
        env:
          USERNAME: ${{ secrets.PUBLISH_GH_USERNAME }}
          TOKEN: ${{ secrets.PUBLISH_GH_TOKEN }}
